services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME}
    volumes:
      - ./:/app:cached
      - ./credentials:/credentials:ro
    working_dir: /app
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/credential_gcp.json
      - AWS_SHARED_CREDENTIALS_FILE=/credentials/credentials_aws
      - AWS_DEFAULT_REGION=${AWS_REGION}
    ports:
      - 127.0.0.1:${LOCAL_PORT}:${CONTAINER_PORT}
    tty: true
